version: '3.8'

services:
  app:
    restart: unless-stopped
    env_file:
      - .env
    image: docktor_app
    hostname: docktor
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["exec", "gunicorn", "run:application", "-b", "localhost:5010"]
    ports:
      - "5010:5010"
